version: '3.8'

services:
  backend:
    build:
      context: ./backend-readwell
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend-readwell
      dockerfile: Dockerfile
    ports:
      - "80:80"
