spring:
  application:
    name: backend-readwell
  datasource:
    url: jdbc:postgresql://localhost:5432/readwell-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      mode: always
